### PR TITLE
refactored into a multi-project build

### PR DESCRIPTION
**Pull request by kensipe**
This is now a multi-project build.   All artifacts can be built at the same time.

idea project config added
build should build the capsule

### CODE REVIEW

**Comment by kensipe** [comment]
@mohitsoni @adam-mesos @smarella The project refactor is in.  I've rebased against the latest and squashed it.  I'm really looking forward to having this merged.   I have plans to add in a number of unit tests after the merge.

**Comment by DarinJ** [comment]
I pulled this down and merged with my code to test.  Works as expected, some documentation will have to be updated.  In particular, the paths in [myriad-remote-distribution-configuration.md](https://github.com/mesos/myriad/blob/phase1/docs/myriad-remote-distribution-configuration.md), [vagrant.md](https://github.com/mesos/myriad/blob/phase1/docs/vagrant.md) and [myriad-dev.md](https://github.com/mesos/myriad/blob/phase1/docs/myriad-dev.md).  Also, `myriad-executor-0.0.1.jar` no longer contains the extra jars dependencies, that's now in `myriad-executor-runnable-0.0.1.jar`.

**Comment by DarinJ** [comment]
@kensipe if you need help with the docs let me know, I think it shouldn't take me that long and I've got some cycles.

**Comment by kensipe** [comment]
the rebase was too painful.  I'm moving this to another PR.  however these notes are so valuable.  I will ask for a review in just a few hours.

**Comment by kensipe** [comment]
This has been replace by PR https://github.com/mesos/myriad/pull/108

Closing this.  Please have a review!!

**Pull request closed without merging**
