### PR TITLE
Corrected Docker Documentation

### PR DESCRIPTION
**Pull request by bgulla**
Removed 'bgulla' from docker name and changed it to mesos/myriad-resourcemanager.

### CODE REVIEW

**Comment by kensipe** [comment]
I would like to test this after the merge on multi-project.    Please give that a review.  I would like to merge that first, then rebase and merge this.

However... this PR is strange.  There are 4 commits for what looks like a 1 file and 4 character change.   We should squash this after the multi-project merge.

**Comment by bgulla** [comment]
I agree, I dont know what happened with the 4 commits, but we really shouldn't need to test-test a documentation change should we?

**Comment by kensipe** [comment]
you can never be too careful... we can never have too many :)   I'll make this correct on a separate PR.  It is really small.

**Comment by kensipe** [comment]
dude... I totally misunderstood.  this is just a readme change.

**Pull request closed without merging**
